# .github/workflows/sync_fork.yml

name: Auto Fork Sync

# 언제 이 액션을 실행할 것인가? -> main 브랜치에 push 이벤트가 발생했을 때
on:
  push:
    branches: ["main"]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. Organization 레포지토리의 최신 코드를 가져온다.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 모든 브랜치 기록을 가져와야 push가 가능하다.
          fetch-depth: 0

      # 2. 개인 Fork 레포지토리로 코드를 Push 한다.
      - name: Push to Fork
        env:
          # 2단계에서 등록한 비밀키(PAT)를 사용한다.
          PAT: ${{ secrets.AUTO_FORK_SYNC_TOKEN }}
        run: |
          git push https://${PAT}@github.com/JayKim0202/ICN-AI-chatbot.git main
